name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    uses: buildcloudio/terraform-registry-template/.github/workflows/module-release.yml@main
    secrets:
      REGISTRY_API_KEY: ${{ secrets.REGISTRY_API_KEY }}